describe ActiveAdminAssets::CompatibilityCheck do
  it 'warns if setup is found that is not compatible with ActiveAdminAssets' do
    # the dummy app has active_admin.css, generated by activeadmin:install
    expect { described_class.call(Rails.application) }.to output(/not compatible/).to_stderr
  end

  it 'does nothing outside development/test' do
    original_env = ENV['RAILS_ENV']
    ENV['RAILS_ENV'] = 'superproduction'
    expect { described_class.call(Rails.application) }.not_to output.to_stderr
  ensure
    ENV['RAILS_ENV'] = original_env
  end

  it 'does nothing if no incompatible setup is found' do
    app = instance_double(Rails::Application, root: Pathname.new(__dir__))
    expect { described_class.call(app) }.not_to output.to_stderr
  end
end
